# See https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
- name: Allow traffic to Kubernetes API server
  community.general.ufw:
    port: "6443"
    rule: allow
    direction: in
    to: '{{cluster_network_host_ip}}'
    comment: Kubernetes API server (cluster network)
- name: Allow traffic to kubelet API
  community.general.ufw:
    rule: allow
    direction: in
    to: '{{cluster_network_host_ip}}'
    port: "10250"
    comment: Kubelet API (cluster network)
