# See https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
- name: Allow traffic to Kubernetes API server
  community.general.ufw:
    port: "6443"
    rule: allow
    comment: Kubernetes API server
- name: Allow traffic to kubelet API
  community.general.ufw:
    port: "10250"
    rule: allow
    comment: Kubelet API
