# See https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cri-o
- name: Load modules for cri-o
  community.general.modprobe: name={{item}} state=present
  loop: [overlay, br_netfilter]
- name: Permanently load crio modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/cri-o.conf
    content: |
      overlay
      br_netfilter
- name: Configure kernel parameters for cri-o
  ansible.posix.sysctl:
    name: '{{item.key}}'
    value: '{{item.value}}'
    reload: true
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
  loop: "{{ items | dict2items }}"
  vars:
    items:
      net.bridge.bridge-nf-call-iptables: "1"
      net.bridge.bridge-nf-call-ip6tables: "1"
      net.ipv4.ip_forward: "1"
- name: Install cri-o
  ansible.builtin.dnf: name=cri-o state=latest
- name: Start cri-o
  ansible.builtin.systemd:
    daemon_reload: true
    unit: crio.service
    enabled: true
    state: started

# See https://github.com/cri-o/cri-o/issues/2411
- name: Remove conflicting network configuration
  ansible.builtin.file:
    path: "/etc/cni/net.d/{{item}}"
    state: absent
  loop:
  - 100-crio-bridge.conf
  - 200-loopback.conf
