- name: Install Arch Linux base system
  hosts: localhost
  tasks:
  # Base setup
  - name: Install packages
    pacman:
      state: present
      name:
      # Btrfs snapshots for backups and recovery
      - snapper
      - snap-pac
      # Tools
      - youtube-dl
      # Networking

      # Development
      - httpie
      - meld
      - code
      - shellcheck
      - shfmt
      - hugo
      - ipython
      - python-pylint
      - autopep8
      - rustup
      - hub
      - github-cli
      - hexyl
      - asciidoctor
      - oxipng

      # Virtual machines
      - virt-manager


      # Office
      - libreoffice-fresh
      - libreoffice-fresh-de
      - hyphen-de
      - hyphen-en
      - hunspell-de
      - hunspell-en_GB
      - hunspell-en_US
      - mythes-de
      - mythes-en
      # Multimedia Apps
      - pavucontrol
      - paprefs
      - gst-plugins-ugly
      - gstreamer-vaapi
      - vlc
      - audacious

      # Dependencies of my scripts
      - python-keyring
      - python-systemd
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    loop:
      # Manage flatpak permissions
      - com.github.tchx84.Flatseal

  - name: Install Gnome
    tags: [gnome]
    pacman:
      state: present
      name:
      - gdm
      - gnome-shell
      - gnome-shell-extensions
      - gnome-tweaks
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - gnome-clocks
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-logs
      - gnome-screenshot
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-weather
      - gnome-terminal
      - seahorse
      - file-roller
      - yelp
      - cheese
      - nautilus
      - gvfs-afc
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - sushi
      - baobab
      - evince
      - eog
      - chrome-gnome-shell
      - remmina
      - simple-scan
      # Gtk Apps
      - gimp
      - inkscape
      - deja-dup

  # Optional deps
  - name: Optional dependencies
    pacman:
      state: present
      extra_args: --asdeps
      name:
        # libva: Intel chipsets
        - intel-media-driver
        # virt-manager: NAT & KVM support
        - dnsmasq
        - ebtables
        - qemu

  # Configuration
  - name: Enable and start services
    systemd:
      unit: "{{ item }}"
      enabled: true
      state: started
    loop:
      # Btrfs snapshots
      - snapper-timeline.timer
      - snapper-cleanup.timer
  - name: Enable multicast DNS name resolution
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: "^hosts: "
      line: "hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns"
  - name: Do not use resolved for multicast DNS (we use Avahi for this)
    lineinfile:
      path: /etc/systemd/resolved.conf
      insertafter: "#MulticastDNS=yes"
      regexp: "^MulticastDNS *="
      line: MulticastDNS=no
    notify:
      - Restart systemd-resolved

  - name: Create directory for dconf profiles
    file:
      path: /etc/dconf/profile
      state: directory
      mode: "0755"
  - name: Define dconf profile for gdm
    copy:
      dest: /etc/dconf/profile/gdm
      mode: "0644"
      content: |
        user-db:user
        system-db:gdm
        file-db:/usr/share/gdm/greeter-dconf-defaults

  - name: Check btrfs subvolumes for better snapper support
    command:
      cmd: "btrfs subvolume show {{ item }}"
    changed_when: False
    loop:
      - /srv
      - /var/tmp
      - /var/log
      - /var/cache
      - /var/cache/pacman/pkg
      - /var/lib/flatpak/repo

  # Boot loader entries
  - name: Install boot loader entries
    copy:
      dest: /boot/loader/entries/{{ item.key }}.conf
      content: |
        title {{ item.value.title }}
        linux /vmlinuz-{{ item.value.linux }}
        initrd /intel-ucode.img
        initrd /initramfs-{{ item.value.linux }}.img
        options quiet
    loop: "{{ items | dict2items }}"
    vars:
      items:
        arch:
          title: Arch
          linux: linux
        arch-lts:
          title: Arch LTS
          linux: linux-lts

  - name: Packages from AUR and my local repo
    pacman:
      state: present
      name:
      - git-gone
      - aurutils
      - otf-vollkorn
      - ttf-fira-go
      - xtermcontrol
      - git-delta
      - numix-circle-icon-theme-git
      - wcal-git

  handlers:
  - name: Restart systemd-resolved
    systemd:
      unit: systemd-resolved
      state: restarted
