- name: Setup repos for runtime and kubernetes
  ansible.builtin.copy:
    src: '{{item}}'
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: "0644"
  with_fileglob: yum.repos.d/*.repo

- import_tasks: container-runtime/docker.yml

# See https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#configure-cgroup-driver-used-by-kubelet-on-control-plane-node
- name: Install kubernetes tools
  ansible.builtin.dnf:
    name: [kubelet, kubeadm, kubectl]
    state: present
    disable_excludes: kubernetes

- name: Configure node IP
  ansible.builtin.copy:
    dest: /etc/sysconfig/kubelet
    content: |
      --node-ip={{cluster_network_host_ip}}
  notify: [Restart kubelet]

- name: Start kubelet
  ansible.builtin.systemd: unit=kubelet.service state=started enabled=true
