- name: Install Arch Linux base system
  hosts: localhost
  tasks:
  # Base setup
  - name: Configure static hosts
    lineinfile:
      path: /etc/hosts
      line: "{{ item }}"
    loop:
      # See <https://wiki.archlinux.org/index.php/Installation_guide#Network_configuration>
      - "127.0.0.1 localhost"
      - "::1 localhost"
  - name: Enable locales
    locale_gen:
      name: "{{ item }}"
    loop:
      - "de_DE.UTF-8"
      - "en_GB.UTF-8"
      - "en_US.UTF-8"
  - name: Configure console
    copy:
      dest: /etc/vconsole.conf
      content: |
        KEYMAP=us
      mode: "0644"
    notify:
      - mkinitcpio
  - name: Set system locale to de_DE.utf8
    copy:
      dest: /etc/locale.conf
      content: |
        LANG=de_DE.UTF-8
      mode: "0644"
  - name: Set timezone
    timezone:
      name: "Europe/Berlin"
  - name: Install base packages
    pacman:
      state: present
      name:
      - base
      - linux-firmware
      - intel-ucode
      - btrfs-progs
      # Kernels
      - linux
      - linux-lts
      # Manage EFI boot loaders
      - efibootmgr
    notify:
      - mkinitcpio
  - name: "Configure kernel modules"
    copy:
      dest: /etc/modprobe.d/lunaryorn-dotfiles.conf
      content: |
        # Blacklist pcspkr to silence beeps
        blacklist pcspkr
        # See https://wiki.archlinux.org/index.php/Power_management
        options snd_hda_intel power_save=1
        options snd_ac97_codec power_save=1
        options iwlwifi power_save=1
        # Prefer function keys over multimedia keys on Apple keyboards
        options hid_apple fnmode=2
        # Configure scrolling for Apple Magic Mouse
        options hid_magicmouse scroll_acceleration=1 scroll_speed=40
  - name: "Configure kernel parameters"
    sysctl:
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      sysctl_file: /etc/sysctl.d/lunaryorn-dotfiles.conf
    loop: "{{ items | dict2items }}"
    vars:
      items:
        # Disable NMI watchdog (powertop rec.)
        kernel.nmi_watchdog: "0"
        # Increase writeback time (default 500, powertop rec.)
        vm.dirty_writeback_centisecs: "1500"
        # The magic SysRq key enables certain keyboard combinations to be
        # interpreted by the kernel to help with debugging. The kernel will respond
        # to these keys regardless of the current running applications.
        #
        # In general, the magic SysRq key is not needed for the average Ubuntu
        # system, and having it enabled by default can lead to security issues on
        # the console such as being able to dump memory or to kill arbitrary
        # processes including the running screen lock.
        #
        # Here is the list of possible values:
        #   0 - disable sysrq completely
        #   1 - enable all functions of sysrq
        #  >1 - enable certain functions by adding up the following values:
        #          2 - enable control of console logging level
        #          4 - enable control of keyboard (SAK, unraw)
        #          8 - enable debugging dumps of processes etc.
        #         16 - enable sync command
        #         32 - enable remount read-only
        #         64 - enable signalling of processes (term, kill, oom-kill)
        #        128 - allow reboot/poweroff
        #        256 - allow nicing of all RT tasks
        #
        #   For example, to enable both control of console logging level and
        #   debugging dumps of processes: kernel.sysrq = 10
        #
        # 128 + 32 + 16
        kernel.sysrq: "176"
        # The following settings are taken from an Ubuntu system; I guess they
        # are reasonable to use.
        #
        # Many files and interfaces contain these addresses (e.g. /proc/kallsyms,
        # /proc/modules, etc), and this setting can censor the addresses. A value
        # of "0" allows all users to see the kernel addresses. A value of "1"
        # limits visibility to the root user, and "2" blocks even the root user.
        kernel.kptr_restrict: "1"
        # IPv6 Privacy Extensions (RFC 4941)
        # ---
        # IPv6 typically uses a device's MAC address when choosing an IPv6 address
        # to use in autoconfiguration. Privacy extensions allow using a randomly
        # generated IPv6 address, which increases privacy.
        #
        # Acceptable values:
        #    0 - don’t use privacy extensions.
        #    1 - generate privacy addresses
        #    2 - prefer privacy addresses and use them over the normal addresses.
        net.ipv6.conf.all.use_tempaddr: "2"
        net.ipv6.conf.default.use_tempaddr: "2"
        # Turn on Source Address Verification in all interfaces to
        # prevent some spoofing attacks.
        net.ipv4.conf.default.rp_filter: "2"
        net.ipv4.conf.all.rp_filter: "2"

  # Packages
  - name: Configure multilib repo
    blockinfile:
      path: /etc/pacman.conf
      content: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
      insertbefore: '^#\[multilib\]'
      marker: '# {mark} ANSIBLE MULTILIB REPO'
    tags: pacman
  - name: Configure pacman
    lineinfile:
      path: /etc/pacman.conf
      insertafter: "^#{{item}}"
      line: '{{item}}'
    loop:
      - Color
      - TotalDownload
    tags: pacman
  - name: Install packages
    pacman:
      state: present
      name:
      - ansible
      - lsb-release
      - fwupd
      - sudo
      - ntfs-3g
      - exfat-utils
      - usbutils
      # Btrfs snapshots for backups and recovery
      - snapper
      - snap-pac
      # Additional pacman tools
      - pacman-contrib
      - pkgfile
      - reflector
      - aurpublish
      - namcap
      # Help
      - man-db
      - man-pages
      - tldr
      # My Shell
      - fish
      - exa
      - fd
      - ripgrep
      - bat
      - trash-cli
      # Tools
      - neovim
      - htop
      - powertop
      - iotop
      - rsync
      - p7zip
      - zip
      - mdcat
      - tree
      - nnn
      - youtube-dl
      - oxipng
      # Networking
      - networkmanager
      - net-tools
      - bind-tools
      - inetutils
      - avahi
      - nss-mdns
      # Package building
      - base-devel
      - devtools
      # Development
      - git
      - httpie
      - jq
      - meld
      - code
      - shellcheck
      - shfmt
      - hugo
      - ipython
      - python-pylint
      - autopep8
      - rustup
      - hub
      - github-cli
      - hexyl
      - asciidoctor
      # Virtual machines
      - virt-manager
      # Desktop services
      - cups
      - hplip
      - bluez
      - sane
      # Desktop
      - flatpak
      - xcursor-pinux
      - xdg-user-dirs
      - materia-gtk-theme
      - xdg-desktop-portal-gtk
      - wl-clipboard
      - keepassxc
      - firefox
      - firefox-i18n-de
      - zathura
      - zim
      - signal-desktop
      - d-feet
      - dconf-editor
      # Office
      - libreoffice-fresh
      - libreoffice-fresh-de
      - hyphen-de
      - hyphen-en
      - hunspell-de
      - hunspell-en_GB
      - hunspell-en_US
      - mythes-de
      - mythes-en
      # Multimedia Apps
      - pavucontrol
      - paprefs
      - gst-plugins-ugly
      - gstreamer-vaapi
      - vlc
      - audacious
      # Fonts
      - noto-fonts
      - noto-fonts-extra
      - noto-fonts-emoji
      - ttf-liberation
      - ttf-caladea
      - ttf-carlito
      - ttf-cascadia-code
      - ttf-fira-code
      - ttf-fira-mono
      - ttf-fira-sans
      - adobe-source-code-pro-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - ttf-roboto
      - ttf-ubuntu-font-family
      - ttf-fira-mono
      - ttf-fira-sans
      # Dependencies of my scripts
      - python-keyring
      - python-systemd
  - name: Install flatpaks
    flatpak:
      name: "{{ item }}"
      state: present
    loop:
      # Manage flatpak permissions
      - com.github.tchx84.Flatseal

  - name: Install Gnome
    tags: [gnome]
    pacman:
      state: present
      name:
      - gdm
      - gnome-shell
      - gnome-shell-extensions
      - gnome-tweaks
      - gnome-calculator
      - gnome-calendar
      - gnome-characters
      - gnome-clocks
      - gnome-disk-utility
      - gnome-font-viewer
      - gnome-logs
      - gnome-screenshot
      - gnome-shell-extensions
      - gnome-system-monitor
      - gnome-weather
      - gnome-terminal
      - seahorse
      - file-roller
      - yelp
      - cheese
      - nautilus
      - gvfs-afc
      - gvfs-goa
      - gvfs-google
      - gvfs-gphoto2
      - gvfs-mtp
      - gvfs-nfs
      - gvfs-smb
      - sushi
      - baobab
      - evince
      - eog
      - chrome-gnome-shell
      - remmina
      - simple-scan
      # Gtk Apps
      - gimp
      - inkscape
      - deja-dup

  # Optional deps
  - name: Optional dependencies
    pacman:
      state: present
      extra_args: --asdeps
      name:
        # zathura: PDF support
        - zathura-pdf-mupdf
        # zim: source code viewing and spell checking
        - gtksourceview3
        - gtkspell3
        # libva: Intel chipsets
        - intel-media-driver
        # virt-manager: NAT & KVM support
        - dnsmasq
        - ebtables
        - qemu

  # Configuration
  - name: Create directory for sudo settings
    file:
      path: /etc/sudoers.d
      state: directory
      mode: "0700"
  - name: Allow wheel group to become root via sudo
    copy:
      dest: /etc/sudoers.d/10-wheel
      content: |
        %wheel ALL=(ALL:ALL) ALL
      mode: "0600"
  - name: Enable and start services
    systemd:
      unit: "{{ item }}"
      enabled: true
      state: started
    loop:
      # Periodically trim file systems
      - fstrim.timer
      # WiFi and network management
      - NetworkManager
      # Home directory & user management
      - systemd-homed
      # Basic NTP sync
      - systemd-timesyncd
      # Hostname resolution
      - systemd-resolved
      # mDNS support
      - avahi-daemon.service
      # pkgfile updates
      - pkgfile-update.timer
      # Pacman cache cleanup
      - paccache.timer
      # Mirrorlist updates
      - reflector.timer
      # Printing
      - org.cups.cupsd.service
      # Bluetooth
      - bluetooth.service
      # Btrfs snapshots
      - snapper-timeline.timer
      - snapper-cleanup.timer
  - name: Enable multicast DNS name resolution
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: "^hosts: "
      line: "hosts: files mymachines myhostname mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns"
  - name: Do not use resolved for multicast DNS (we use Avahi for this)
    lineinfile:
      path: /etc/systemd/resolved.conf
      insertafter: "#MulticastDNS=yes"
      regexp: "^MulticastDNS *="
      line: MulticastDNS=no
    notify:
      - Restart systemd-resolved
  - name: Redirect resolv.conf to systemd-resolved
    file:
      src: /run/systemd/resolve/stub-resolv.conf
      dest: /etc/resolv.conf
      state: link
  - name: Create directory for dconf profiles
    file:
      path: /etc/dconf/profile
      state: directory
      mode: "0755"
  - name: Define dconf profile for gdm
    copy:
      dest: /etc/dconf/profile/gdm
      mode: "0644"
      content: |
        user-db:user
        system-db:gdm
        file-db:/usr/share/gdm/greeter-dconf-defaults
  - name: Configure font settings
    file:
      src: "../conf.avail/{{ item }}.conf"
      dest: "/etc/fonts/conf.d/{{ item }}.conf"
      state: link
    loop:
      # Hinting and subpixel aliasing
      - 10-hinting-slight
      - 10-sub-pixel-rgb
      # LCD filter, see https://wiki.archlinux.org/index.php/Font_configuration#LCD_filter
      - 11-lcdfilter-default
  - name: Configure mirrorlist updates
    copy:
      dest: /etc/xdg/reflector/reflector.conf
      content: |
        --save /etc/pacman.d/mirrorlist
        --protocol https
        --country Germany
        --latest 5
        --sort age

  - name: Check btrfs subvolumes for better snapper support
    command:
      cmd: "btrfs subvolume show {{ item }}"
    changed_when: False
    loop:
      - /srv
      - /var/tmp
      - /var/log
      - /var/cache
      - /var/cache/pacman/pkg
      - /var/lib/flatpak/repo

  # Boot loader entries
  - name: Install boot loader entries
    copy:
      dest: /boot/loader/entries/{{ item.key }}.conf
      content: |
        title {{ item.value.title }}
        linux /vmlinuz-{{ item.value.linux }}
        initrd /intel-ucode.img
        initrd /initramfs-{{ item.value.linux }}.img
        options quiet
    loop: "{{ items | dict2items }}"
    vars:
      items:
        arch:
          title: Arch
          linux: linux
        arch-lts:
          title: Arch LTS
          linux: linux-lts

  # Local AUR repo
  - name: Create pkgrepo dir
    file:
      name: /srv/pkgrepo
      state: directory
      mode: "0755"
  - name: Create aur repo subvolume
    command:
      cmd: btrfs subvolume create /srv/pkgrepo/aur/
      creates: /srv/pkgrepo/aur/
  - name: Check that the aur directory is a subvolume
    command:
      cmd: btrfs subvolume show /srv/pkgrepo/aur/
    changed_when: False
  - name: Initialize package database
    command:
      cmd: repo-add /srv/pkgrepo/aur/aur.db.tar.xz
      creates: /srv/pkgrepo/aur/aur.db.tar.xz
  - name: Set default ACL for /srv/pkgrepo/aur to allow all users to read files regardless
    acl:
      path: "/srv/pkgrepo/aur"
      default: true
      state: present
      follow: no
      etype: other
      permissions: "r--"
  - name: Configure AUR repository
    blockinfile:
      path: /etc/pacman.conf
      content: |
        [aur]
        SigLevel = Optional TrustAll
        Server = file:///srv/pkgrepo/aur
      marker: '# {mark} ANSIBLE LOCAL AUR REPO'
    tags: pacman

  - name: Packages from AUR and my local repo
    pacman:
      state: present
      name:
      - git-gone
      - aurutils
      - otf-vollkorn
      - ttf-fira-go
      - xtermcontrol
      - git-delta
      - numix-circle-icon-theme-git
      - wcal-git
      - etc-update

  handlers:
  - name: Restart systemd-resolved
    systemd:
      unit: systemd-resolved
      state: restarted
  - name: Restart systemd-timesyncd
    systemd:
      unit: systemd-timesyncd
      state: restarted
  - name: "mkinitcpio"
    command: mkinitcpio -p linux linux-lts
