- name: Webserver
  hosts: swsnr.de
  roles:
    - name: hcloud-server-base
    - name: hcloud-caddy2
    - name: hcloud-website
    - name: hcloud-postgresql
- name: Kubernetes nodes
  hosts: [kcp1.swsnr.de]
  roles:
  - hcloud-server-base
  - hcloud-k3s-base
- name: Kubernetes control plane nodes
  hosts: [kcp1.swsnr.de]
  roles:
  - hcloud-k3s-server
- name: Kubernetes ingress node
  hosts: [kcp1.swsnr.de]
  tasks:
  - name: Open HTTP/HTTPS ports
    community.general.ufw:
      port: '{{item}}'
      rule: allow
      comment: HTTP traffic to this k3s node
    loop: [http, https]

- name: Kubernetes website node
  hosts: [kcp1.swsnr.de]
  tasks:
  - name: Create /srv/http
    ansible.builtin.file:
      path: /srv/http
      state: directory
      owner: root
      group: root
      mode: '0755'
  - name: Create transfer group for website
    ansible.builtin.group:
      name: website
      state: present
  - name: Create transfer user for website
    ansible.builtin.user:
      name: website
      group: website
      password_lock: true
  - name: Register deploy key
    ansible.posix.authorized_key:
      comment: website deployment
      key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAdsMybfcof27TBl8qDKof+ugcKecoP3n2mggwPExGtc
      user: website
      key_options: 'command="/usr/local/bin/rrsync /srv/http/swsnr.de",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding'
  - name: Create /srv/http/swsnr.de
    ansible.builtin.file:
      path: /srv/http/swsnr.de
      state: directory
      owner: website
      group: website
      mode: '0755'
